version: "3.9"

services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: crbs-nginx
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - app:/var/www/html
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: crbs-php
    links:
      - mariadb
    expose:
      - 9000
    volumes:
      - app:/var/www/html
  mariadb:
    image: mariadb:10
    container_name: crbs-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: securePassword123
      MARIADB_DATABASE: crbs_db
      MARIADB_USER: crbs_user
      MARIADB_PASSWORD: 6vTccw7zYF
    volumes:
      - db:/var/lib/mysql 

volumes:
  app:
  db:
