version: "3.9"

services:
  nginx:
    build: ./nginx/
    container_name: crbs-nginx
    ports:
      - "8080:80"
    links:
      - php
    volumes_from:
      - app-data
    depends_on:
      - app-data
  php:
    build: ./php/
    container_name: crbs-php
    links:
      - mariadb
    expose:
      - 9000
    volumes_from:
      - app-data
    depends_on:
      - app-data
  app-data:
    image: php:7.3-fpm  
    container_name: app-data-container  
    volumes:
      - ../application/:/var/www/html/application/  
      - ../assets/:/var/www/html/assets/  
      - ../local/:/var/www/html/local/  
      - ../uploads/:/var/www/html/uploads/  
      - ../index.php:/var/www/html/index.php
      - ../facivon.ico:/var/www/html/favicon.ico
      - ../LICENSE.txt:/var/www/html/LICENSE.txt
    command: "true"
  mariadb:
    image: mariadb:10
    container_name: crbs-mariadb
    expose:
      - 3306
#    ports:
#      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: securePassword123
      MARIADB_DATABASE: crbs_db
      MARIADB_USER: crbs_user
      MARIADB_PASSWORD: 6vTccw7zYF
    volumes:
      - db:/var/lib/mysql 

volumes:
  db:
